version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            sudo apt-get install -y git tzdata openssh-server libffi-dev net-tools autoconf automake libtool libssl-dev make
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Perform test
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
            cd tests
            pytest test_bbclib.py
            pytest test_bbclib2.py
            pytest test_keypair.py
            pytest test_bbclib_idlen.py
            pytest test_bbclib_nopubkey.py
            pytest test_bbclib_pack_unpack.py
            pytest test_bbclib_assets_v2.py
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
      - run:
          name: verify version
          command: |
            . venv/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
      - run:
          name: deploy in PyPI
          command: |
            . venv/bin/activate
            pip install wheel twine
            rm -rf dist/ bbclib.egg-info/
            python setup.py sdist
            python setup.py bdist_wheel
            twine upload --repository pypi dist/*
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"
            - "libs"
